/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import static main.ScreenSize.width;

/**
 *
 * @author Nguyen Quoc Nhan
 */
public final class Menu extends javax.swing.JFrame {
    
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xi Trum An Num");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final JFrame mn = new JFrame();
                URL menu = this.getClass().getResource("/image/menu.jpg");
                int frameWidth = new ImageIcon(menu).getIconWidth();
                int frameHeight = new ImageIcon(menu).getIconHeight();
                mn.setSize(frameWidth, frameHeight);
                mn.setUndecorated(true);
                int width;
                int height;
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                width = (int) screenSize.getWidth();
                height = (int) screenSize.getHeight();
                mn.setLocation(width/2 - frameWidth/2  ,height/2 - frameHeight/2);
                mn.setVisible(true);
                mn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                mn.setResizable(false);
                mn.setContentPane(new JLabel(new ImageIcon(menu)));
                mn.setLayout(new BorderLayout());
                URL play = this.getClass().getResource("/image/play_button.gif");
                JLabel play_button = new JLabel(new ImageIcon(play));
                play_button.addMouseListener(new MouseAdapter(){
                    @Override
                    public void mousePressed(MouseEvent e){
                        Window.main();
                        mn.setVisible(false);
                    }
                });
                mn.add(play_button,BorderLayout.WEST);
                URL quit = this.getClass().getResource("/image/quit.png");
                JLabel quit_button = new JLabel(new ImageIcon(quit));
                quit_button.addMouseListener(new MouseAdapter(){
                    @Override
                    public void mousePressed(MouseEvent e){
                        System.exit(1);
                    }
                });
                mn.add(quit_button,BorderLayout.AFTER_LINE_ENDS);
                Toolkit toolkit = Toolkit.getDefaultToolkit();
                URL cursor = this.getClass().getResource("/image/cursor.png");
                Image image = toolkit.getImage(cursor);
                Cursor c = toolkit.createCustomCursor(image , new Point(0,0),null);
                mn.setCursor(c);
            }
        }       
        );
    }
}
